#!/bin/sh
### BEGIN INIT INFO
# Provides:          con-check
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Internet connection check
# Description:       Internet connection status checker
### END INIT INFO

dir="/usr/local/bin/"
cmd="con-check"

name=`basename $0`
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

case "$1" in
    start)
    if pgrep -x "$cmd" >/dev/null 2>&1 ; then
        echo "Already started"
    else
        echo -n "Starting $name"
        $dir$cmd >> "$stdout_log" 2>> "$stderr_log" &
        for i in 1 2 3 4 5 6 7 8 9 10
        do
            if pgrep -x "$cmd" >/dev/null 2>&1 ; then
                break
            fi
            echo -n "."
            sleep 1
        done
        echo

        if ! pgrep -x "$cmd" >/dev/null 2>&1 ; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        else
            echo "Started"
        fi
    fi
    ;;
    stop)
    if pgrep -x "$cmd" >/dev/null 2>&1 ; then
        echo -n "Stopping $name"
        pkill -INT -x $cmd
        for i in 1 2 3 4 5 6 7 8 9 10
        do
            if ! pgrep -x "$cmd" >/dev/null 2>&1 ; then
                break
            fi
            echo -n "."
            sleep 1
        done
        echo

        if pgrep -x "$cmd" >/dev/null 2>&1 ; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if pgrep -x "$cmd" >/dev/null 2>&1 ; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if pgrep -x "$cmd" >/dev/null 2>&1 ; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0